pg_recvlogical \
    --file=- \
    --dbname=postgresql://oliverrice@localhost:28814/walrus \
    --plugin=wal2json \
    --option=include-pk=1 \
    --option=include-transaction=false \
    --option=include-timestamp=true \
    --option=include-type-oids=true \
    --option=format-version=2 \
    --option=actions=insert,update,delete \
    --slot=realtime \
    --create-slot \
    --if-not-exists \
    --start
