version: '3'
services:
  db:
    container_name: walrus_streaming
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "5501:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - fsync=off
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
