name: WALRUS worker tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: worker tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: supabase/postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5501:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: run tests
        run: |
          cd worker
          cargo test --bin walrus -- --test-threads=1
